"""Generate a compact ASCII connection-screen font; requires Pillow."""
from pathlib import Path
from PIL import Image, ImageDraw, ImageFont

root = Path(__file__).resolve().parents[1]
font = ImageFont.load_default(size=12)
rows = []
for code in range(32, 127):
    image = Image.new('1', (8, 14))
    ImageDraw.Draw(image).text((0, 0), chr(code), fill=1, font=font)
    rows.append('    {' + ','.join(str(sum((1 << x) for x in range(8) if image.getpixel((x, y)))) for y in range(14)) + '}')
(root / 'firmware/badge/main/badge_font.h').write_text(
    '// Generated by tools/generate-badge-font.py (Pillow default font).\n'
    '#pragma once\n#include <stdint.h>\nstatic const uint8_t badge_font[95][14] = {\n'
    + ',\n'.join(rows) + '\n};\n', encoding='utf-8')
