"""Rasterize the small Chinese UI vocabulary; Pillow and Microsoft YaHei required."""
import json
from pathlib import Path
from PIL import Image, ImageDraw, ImageFont

ROOT = Path(__file__).resolve().parents[1]
PHRASES = {
    'TITLE': '无线小森林',
    'LIVE': '正在观察身边的信号',
    'DEMO': '演示风景',
    'STRONG': '这棵树的信号很强',
    'MEDIUM': '这棵树的信号适中',
    'WEAK': '这棵树的信号较弱',
    'FADING': '这棵树的信号正在消失',
    'WAITING': '正在寻找附近的信号',
    'EMPTY': '还没有发现附近的信号',
    'RETRY': '暂时没看清，正在重试',
    'HIDDEN': '隐藏网络',
    'HELP': '上下选树　长按下键切换',
}

font = ImageFont.truetype('C:/Windows/Fonts/msyh.ttc', 16)
entries = []
lines = ['// Generated by tools/generate-ecology-labels.py', '#pragma once',
         '#include <stdint.h>', 'typedef struct { uint16_t width; const uint8_t *bits; } eco_label_bitmap;']
for key, phrase in PHRASES.items():
    width = int(font.getlength(phrase))
    im = Image.new('1', (width, 22))
    ImageDraw.Draw(im).text((0, 0), phrase, font=font, fill=1, stroke_width=0)
    bits = [int(v != 0) for v in im.getdata()]
    packed = [sum(bits[i+j] << (7-j) for j in range(min(8, len(bits)-i))) for i in range(0, len(bits), 8)]
    lines.append(f'static const uint8_t label_{key}[] = {{{",".join(map(str, packed))}}};')
    entries.append({'id': key, 'text': phrase, 'width': width, 'bits': packed})
lines.append('enum { ' + ', '.join('UI_' + k for k in PHRASES) + ' };')
lines.append('static const eco_label_bitmap eco_labels[] = {')
lines.extend(f'    {{{e["width"]}, label_{e["id"]}}},' for e in entries)
lines.append('};\n')
(ROOT / 'firmware/wireless-ecology/main/ecology_labels.h').write_text('\n'.join(lines), encoding='utf-8')
(ROOT / 'firmware/wireless-ecology/test_labels.json').write_text(json.dumps(entries, ensure_ascii=False), encoding='utf-8')
print('Generated Chinese labels:', len(entries))
